In [8]:
import numpy as np
from faker import Faker
import random

fake = Faker()
num_freelancers = 1000
names = [fake.name() for _ in range(num_freelancers)]


freelancer_matrix = np.array([[round(random.uniform(1, 10), 1) for _ in range(3)] for _ in range(num_freelancers)])

print("Matrix Shape:", freelancer_matrix.shape)
print("First Freelancer:", names[0], "-> Vector:", freelancer_matrix[0])
print(freelancer_matrix)

Matrix Shape: (1000, 3)
First Freelancer: Samantha Melendez -> Vector: [9.1 8.4 3.9]
[[9.1 8.4 3.9]
 [2.  3.1 5.9]
 [2.2 2.8 5.6]
 ...
 [3.7 4.6 7.2]
 [2.7 3.1 4. ]
 [7.8 7.  6.7]]


# Define Cosin Similarity

In [31]:
target = np.array([9.0, 4.0, 8.0])

dot_product = freelancer_matrix @ target

matrix_norms = np.linalg.norm(freelancer_matrix, axis=1)

target_norm = np.linalg.norm(target)

scores = dot_product / (matrix_norms * target_norm)
print(scores[868])

print(scores[362])


top_3_indices = np.argsort(scores)[::-1][:3]
print(top_3_indices)

print("--- Top 3 Best Matches (Cosine) ---")
for idx in top_3_indices:
    print(f"Name: {names[idx]} | Vector: {freelancer_matrix[idx]} | Match Score: {scores[idx]:.4f}")




0.5194613655517929
0.9998657106401121
[362 420 582]
--- Top 3 Best Matches (Cosine) ---
Name: Travis James | Vector: [9.2 4.  7.9] | Match Score: 0.9999
Name: Destiny Hoffman | Vector: [8.7 3.5 7.2] | Match Score: 0.9992
Name: Jose Ramirez | Vector: [9.5 4.1 7.7] | Match Score: 0.9991
